#docker-compose.yml

services:
  fastapi-backend:
    build: .
    ports:
      - "8080:80"
    networks:
      - example-network-techni
  mongodb:
    image: mongo:7
    ports:
      - '27018:27017'
    volumes:
      - "C:/Users/styda/data/techni-db:/data/db"
    networks:
      - example-network-techni

networks:
  example-network-techni:
    driver: bridge